### ISSUE TITLE
Tests and continuous integration bot

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/spotipy#10]
As you created some issues to track some features and ideas, I thought this would be useful too. [plamere/spotipy](https://github.com/plamere/spotipy) has plenty of tests we could clean and maybe refactor to suit this API. Also, a continuous integration bot like Travis CI could help with these tests. What do you think?

**Comment by felix-hilden** [comment]
I'm positive about writing unit tests for functions like `convert.to_uri` to confirm their functionality and such. I'm not sure what's the utility of writing tests against the API calls (which a load of the tests seem to be about). They could be useful though 👌

Travis - no experience with it but I've seen it in lot's of repositories. Once we have some tests it could very well be worth it to put it up!

**Comment by felix-hilden** [comment]
Travis up now with some tests, I'll start looking at a more comprehensive set of tests.
