### ISSUE TITLE
Refreshing client token

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#101]
Currently the client token is "refreshed" the same way as user tokens in `util.RefreshingToken`. This will not work, as the token has no refresh token, but needs to be requested from the credentials again.

The refresh token is `None`, which can be used to check if it is a client token. In that case, request a new one instead of trying to refresh.

**Comment by marioortizmanero** [comment]
I was about to post a bug related to this. The error I'm getting is: 

```
Traceback (most recent call last):
  File "/home/mario/Programming/spotify-music-videos/spotivi
ds/gui/window.py", line 108, in on_api_selection
... (more stuff of my project)
  File "/home/mario/Programming/spotify-music-videos/spotivi
ds/api/spotify/web.py", line 164, in get_token
    s.playback_currently_playing()
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/client/player/view.py", line 57
, in playback_currently_playing
    json = self._get('me/player/currently-playing', market=m
arket)
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/client/base.py", line 139, in _
get
    return self._request('GET', url, payload=payload, params
=params)
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/client/base.py", line 133, in _
request
    request = self._build_request(method, url)
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/client/base.py", line 96, in _b
uild_request
    'Authorization': f'Bearer {self.token}',
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/client/base.py", line 66, in to
ken
    return str(self._token)
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/auth.py", line 62, in __str__
    return self.access_token
  File "/home/mario/Programming/spotify-music-videos/lib/pyt
hon3.8/site-packages/spotipy/util.py", line 84, in access_to
ken
    self._token = self.credentials.refresh(self._token)
AttributeError: 'RefreshingCredentials' object has no attrib
ute 'refresh'
```

**Comment by felix-hilden** [comment]
Hmm, that error is on a user-related endpoint.. This needs some more testing. Thanks for the traceback!

**Comment by marioortizmanero** [comment]
It could be my fault though, I do weird stuff with tokens and such because I have to save the info in a config file. But the error doesn't seem to say much. Here's the code:

```
    # Checking that the credentials are valid
    for c in (auth_token, refresh_token, expiration, client_id, client_secret,
              redirect_uri):
        if c in (None, ''):
            logging.info("Rejecting the token because one of the credentials"
                         " provided is empty.")
            return None

    # Generating a RefreshingToken with the parameters
    data = {
        'access_token': auth_token,
        'token_type': 'Bearer',
        'scope': scopes.user_read_currently_playing,
        'expires_in': expiration - int(time.time()),
        'refresh_token': refresh_token
    }
    creds = RefreshingCredentials(client_id, client_secret, redirect_uri)
    token = RefreshingToken(Token(data), creds)

    # Doing an initial request to check that it was generated correctly:
    # an error could be raised from the requests package, or the returned
    # value could be None
    try:
        s = Spotify(token)
        s.playback_currently_playing()
    except (ConnectionNotReady, requests.exceptions.HTTPError) as e:
        # Note: logging messages use the old formatting instead of f-strings
        # because of efficiency (and more). If logging was disabled, Python
        # shouldn't compute the string format.
        logging.info("Rejecting the token because of an error while trying"
                     " to connect to Spotify: %s", str(e))
        return None
```

[Full code](https://github.com/marioortizmanero/spotify-music-videos/blob/next/spotivids/api/spotify/web.py)

**Comment by felix-hilden** [comment]
Oh! You are instantiating the `RefreshingToken` with `RefreshingCredentials`! That's the reason it can't find the `refresh` method. I think this is unrelated. Instantiate it with `RefreshingCredentials._client` instead. The refreshing version does not inherit the auth client and pass itself because it would then result in recursive refreshing tokens. Maybe I should add a remark to the documentation too.

**Comment by marioortizmanero** [comment]
Okay, that was it!

I'm constructing the token like this because its data has to be saved inside a config file. That way, after the app is closed, the token can be restored from the config file and I avoid creating a new token every time the app is launched. This was done in the past with Plamere's own cache token, but it was a bad solution because the token was saved wherever the app was launched and left files all over your computer (and it didn't support RefreshingToken). Also, my app already has a very good config module so it was easy to implement :)

**Comment by felix-hilden** [comment]
Right! Have you considered just saving the refresh token and using [`util.request_refreshed_token`](https://github.com/felix-hilden/spotipy/blob/master/spotipy/util.py#L328) as suggested [here](https://updated-spotipy-test.readthedocs.io/en/latest/documents/advanced_usage.html#token-persistence)? I guess if you want to avoid creating new tokens your approach is the way to go, but it isn't much work, and they expire in an hour anyway.

**Comment by marioortizmanero** [comment]
Oh I didn't know about that! Very neat function. So does that work when the refresh token is expired too?

**Comment by felix-hilden** [comment]
In my experience they don't expire. I've used one for months in our Travis tests. And if they do, the full token certainly has no use. So that would be the moment to request authentication again.

**Comment by marioortizmanero** [comment]
Thanks a lot for the tip then! It definitely simplifies a lot of stuff. I'll update it so that it only uses the refresh token :)

**Comment by pixelicous** [comment]
I just started using this Spotipy.. trying to following your token tips here.. too ahead of me at the moment i think :) i thought the token refresh is done automatically inside the methods in case the token is invalid. Did one of you try working with django? first thing i wanna do is get the token directly from the return uri trying to get the token from the return uri

**Comment by felix-hilden** [comment]
Yes, that's true for the user token, and after closing this true for the client token as well :D I'm not experienced with Django, but I have written an [example](https://updated-spotipy-test.readthedocs.io/en/latest/examples/auth_server.html) in Flask, perhaps that could be used.

**Comment by pixelicous** [comment]
> Yes, that's true for the user token, and after closing this true for the client token as well 
@felix-hilden  - didnt get what you mean :)

**Comment by felix-hilden** [comment]
No problem, have a look at the documentation and you'll get up and running in no time!

**Comment by pixelicous** [comment]
@felix-hilden - already on it, btw is that link the most up to date documentation? why not link to it from github?

**Comment by felix-hilden** [comment]
I don't quite follow. That link is to the latest build of the documentation, also linked to from the GitHub readme both in the `docs: passing` banner and the introduction.
