### ISSUE TITLE
Using f-strings

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/spotipy#11]
Since the required version is python 3.7, you could consider implementing f-strings in some parts of the module. It's a small thing but I've seen it several times while looking at your code and I think it could help readibility, like in [this](https://github.com/felix-hilden/spotipy/blob/master/spotipy/client/base.py#L20) example.

```python
return 'http status: {0}, code:{1} - {2}'.format(
    self.http_status, self.code, self.msg)
```

could be replaced with 

```python
return f'http status: {self.http_status}, code:{self.code} - {self.msg}'
```

I can do a PR myself if you want, but I wanted to ask what you think about it first.

**Comment by felix-hilden** [comment]
Let's do that! I'm a bit unsure whether it will improve the readability for example in the case you mentioned, but I think in general in the client it will, as there usually is one or two parameters. But for consistency it is perhaps best to use them everywhere.

**Comment by marioortizmanero** [comment]
I use a PEP8 linter and it throws a few errors. Should I include some PEP8 recommendations too? For example often the 79 characters limit is passed.

**Comment by felix-hilden** [comment]
Thank you! And yeah, I'm always up for style improvements. It seems PyCharm's line length was 120 by default. Changed that to 79 for me as well!

**Comment by marioortizmanero** [comment]
I'll send some commits to fix it and you can just choose what you want then :)
