### ISSUE TITLE
Access user playback queue

### ISSUE THREAD

**Issue by Excidion** [felix-hilden/spotipy#110]
I am wondering if there is any support for accessing the current playback queue of a user possible/planned/available.

Could not find any mention of it in the RTD documentation.

**Comment by felix-hilden** [comment]
Hi, sadly no. The queue functionality has not been provided by the Web API even though skipping to the next song using the API still consumes the queue. [This issue](https://github.com/spotify/web-api/issues/462) on Spotify's tracker will be updated with the most recent information. Let's hope that this changes soon.

I'll mark this issue for tracking and close it until we receive new information.

**Comment by felix-hilden** [comment]
@Excidion Some queue functionality has been added to the API. We'll implement it as soon as possible. Follow the linked issue for details. I'll stop tracking this issue now.
