### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/spotipy#116]
Hi Felix,

I wanted to know your opinon about supporting Python 3.6. I know this module heavily uses dataclasses, but there's not much more to Python 3.7. You can use the [backported](https://pypi.org/project/dataclasses/) module, or the [attrs](http://www.attrs.org/en/stable/) project. The former should be exactly the same as python 3.7's implementation, and attrs seems to be a different approach but that could be interesting. But the thing is that it doesn't seem that hard to implement on your module. 

My app also supports Python 3.7 but I've realized that python 3.6 is still used too much to not support it. Ubuntu 18.04, the latest LTS (amongst other distributions and BSDs), is still being used and will be supported until 2023. I think this could also help get more people using the module, which would be beneficial.  Python 3.6 is still going to be supported until approximately 2021-12.

What do you think?

E: Also, happy new year Felix! To a great open source year! :)

**Comment by felix-hilden** [comment]
I'm all for it!

I've heard of the backport, but not of attrs. I glanced over it, and it actually seems quite nice. I'll have to check out its advanced features. If they are useful, we could consider moving to attrs. If not, we should figure out a neat way of creating version-specific dependencies. If there's no cleaner way, then just examine the system python version in setup and install dataclasses from PyPI on 3.6. I'll investigate more.

Happy new year to you too, Mario! You've been a great help for me. I appreciate it 👌 To a great open source year!

**Comment by marioortizmanero** [comment]
> I've heard of the backport, but not of attrs. I glanced over it, and it actually seems quite nice. I'll have to check out its advanced features. If they are useful, we could consider moving to attrs.

Attrs has really good and detailed explanations you can check out http://www.attrs.org/en/stable/index.html

> If not, we should figure out a neat way of creating version-specific dependencies. If there's no cleaner way, then just examine the system python version in setup and install dataclasses from PyPI on 3.6. I'll investigate more.

Don't worry about that, it's very easy to do: https://stackoverflow.com/questions/21082091/install-requires-based-on-python-version.

> Happy new year to you too, Mario! You've been a great help for me. I appreciate it ok_hand To a great open source year!

I'm glad I can be of help, you've really worked on this project and I love it :)

**Comment by felix-hilden** [comment]
Thanks a bunch!
