### ISSUE TITLE
Renaming Spotipy

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#121]
The situation has changed a bit recently. Plamere, the original owner of the Spotipy package has responded and given rights to the original repository. So it might very well be that development will continue there. A few contributors were invited, myself included. But they do not share the vision I based my version on. The third new contributor, Harrison has yet to express his views on the matter. In case this repository parts ways with the original package, we need a new name. Better to prepare already.

What should that potential new name be? I have some ideas, but I'd love to hear any suggestions as well!

- `spotipy3`: An obvious candidate. This library is based on Plamere's, so it could carry on the name. It shows the history with `spotipy` and implies an improvement over the previous version.
- `spoton`: Another name combination of Spotify and Python. Unique (and available on PyPI), easier to write and is coincidentally also the adjective "spot on", again implying good quality.

How much easier to write? A lot actually. Using two hands on a qwerty keyboard "spotipy3" requires `s+po+t+ip+y3 = 5` steps or bursts or hand positions, "spoton" only `s+po+t+on = 4`. In addition, "spoton" only requires the right hand to burst twice in the same direction, while "spotipy3" requires both directions (`p->o + i->p`) on the right hand and one burst from the left. Don't know about you guys, but to me this is worth considering.

Renaming should not be such a big deal yet. We've had no releases. Documentation and other things need to be updated, but GitHub provides automatic redirects from felix-hilden/spotipy to whatever it shall be.

We are running out of Pythonic library names soon, now Spotipy, Spoton, Pyfy, next Fyton :D

**Comment by felix-hilden** [comment]
Some logo concepts, what do you think, favorites?

![1](https://user-images.githubusercontent.com/25202257/71768250-259fad00-2f1d-11ea-9cbf-52100c6232d6.png)
![3](https://user-images.githubusercontent.com/25202257/71768253-2a646100-2f1d-11ea-8833-af2690c905e1.png)
![2](https://user-images.githubusercontent.com/25202257/71768255-2c2e2480-2f1d-11ea-9ad9-61b8ae37a2a7.png)

**Comment by marioortizmanero** [comment]
After seeing the discussion on plamere/spotipy, I don't think spotipy is a good idea anymore. It seems like they are going to continue its development in there and it could confuse people if they end up releasing a version 3 in the future (although the logo looks super cool).

Spoton is a better name but maybe it sounds a bit weird? Almost like it's a travel agency or a web engine, it doesn't really sound to Spotify. Maybe I'm too picky at names hehe. But you're right, there aren't many other names to pick... Maybe Spothon? Spotilib? Libfy?

Here's how they came up with Spotify, maybe it will inspire you :P

> Spotify was developed in 2006[13] by a team in Stockholm, Sweden. The company was founded by Daniel Ek, former CTO of Stardoll, and Martin Lorentzon, co-founder of TradeDoubler. The company's title, according to Daniel Ek, was initially misheard from a name shouted by Martin Lorentzon. Later they thought out an etymology of a combination of "spot" and "identify".[14] Spotify operates internationally under a multitude of companies in different regions. Spotify currently has 44 offices that operate internationally.

**Comment by felix-hilden** [comment]
That's true, Spotipy3 would make more sense for a discontinued package. Maybe Spoton is a bit weird, but I wouldn't take it off the table for it. Of your suggestions I like Spothon the most. A few more ideas flailing around:
- `spotil`: No special background, maybe Spotify + Util. Easy to write.
- `spotnir`: From Sleipnir, Odin's horse from the Norse mythology. About the same writing effort as Spotipy, but a bit awkward to pronounce for English folks.
- `bifrost`: A slightly butchered version of Bifröst, the bridge between Earth and the gods, much like this library is a bridge. A fun one first and foremost 😄 
- `apollo`: From the Greek god of music (among other things), or `spollo`. A bit difficult to write because all of the right-hand action.
- `tekore`: From Terpsichore, the Greek muse for song and dance. Easy to write.

And I couldn't come up with anything from this, but it's an interesting character:
- Ihy: Egyptian god of music and joy (I guess `spotihy`, but that's not good)

I mean, there are plenty of libraries whose names have nothing to do with their domain. But the name would have to be good.

**Comment by marioortizmanero** [comment]
So you're into mythology, eh? These names sound really cool to be honest. You could also go for a completely unrelated name if you wanted to. My favorites of those are `tekore` or `spotil`. `bifrost`'s meaning is more interesting but I don't think anyone will actually know what it means anyway.

**Comment by felix-hilden** [comment]
Well I've found it to be a good source of inspiration :D Yeah, mine too. Let's let it sit for a while and make a decision when things resolve in the original repo.

**Comment by felix-hilden** [comment]
Sadly `bifost` is reserved on PyPI. So here are the top candidates:

- `spotil` - boring but descriptive, could also be `spotils`
- `tekore` - weird but unique, would be better if this would be generally about music

Let's try to choose one rather quickly. Now that we have less business with Spotipy there's no use in delaying launch on PyPI any longer. I'll try to come up with some logo ideas too.

**Comment by felix-hilden** [comment]
Here are some new logo concepts.
![spotil](https://user-images.githubusercontent.com/25202257/72209098-8bf37500-34b3-11ea-8f3d-fce11726e7d1.png)
![spotils](https://user-images.githubusercontent.com/25202257/72209101-8e55cf00-34b3-11ea-8f76-aa712b6063d6.png)
![tekore2](https://user-images.githubusercontent.com/25202257/72209107-9150bf80-34b3-11ea-88b8-4ff12f18399b.png)
![tekore3](https://user-images.githubusercontent.com/25202257/72209108-9281ec80-34b3-11ea-958d-f50262655fbf.png)

**Comment by marioortizmanero** [comment]
I like both Spotil and Spotils, but I'm not sure what's better. If I had to choose one I'd go with `spotil` just because it's shorter and easier to pronounce, but both are good.

**Comment by felix-hilden** [comment]
Let's consider `spotil` then, that would be my pick out of the two as well. So we have a final two, `spotil` and `tekore`. Which one do you prefer? How bout @jingw222, any opinions?

It would be fun to choose the fun one. And I'd rather have an interesting name and a library with a bit of personality, but there are real merits to a descriptive name. It's not a problem for well-known, huge libraries, but we're not one - yet at least.

**Comment by marioortizmanero** [comment]
If you want the fun name you can absolutely go with that. But in that please do change the logo's font. It seems to be Papyrus or a very similar font, which is basically a meme :rofl:.

**Comment by felix-hilden** [comment]
Papyrus exactly 😆! I'm no designer... The small 's' in Spotils is just a scaled down version of the capital S because I don't have the Spotify font, but those were just for quick demo :D I'll have to look at it more carefully when we choose what to go for.

**Comment by jingw222** [comment]
I'd personally go with `tekore` if those two are the only finalists. There already exist plenty of similar packages whose names are just portmanteaus of "python" and "spotify" in one form or another. It makes it hard to distinguish between them, and often people get frustrated for that (or it's only me 😅). Anyway, the logo is fine, best if you could represent some elements related to Python, like a python head and a tail on each side of the instruments. Don't know if I get it across.

**Comment by felix-hilden** [comment]
Thanks a lot! Do suggest if you have something else in mind though, the two need not be the only alternatives. Those are some good points. I like the idea of a snake head in the lyre. `from tekore import Spotify` is a bit odd compared to Spotil, but it's not horrible.

**Comment by jingw222** [comment]
Yes it looks a little weird, but only because of the fact that we're currently not accustomed to that name. Imagine If the library became a household name one day, like `keras` in the deep learning world. ;)

**Comment by felix-hilden** [comment]
Yep, that exactly was my reference too :D Let's strive to be that household name then! I'll start the renaming process and provide new logo alternatives.

**Comment by felix-hilden** [comment]
I have three iterations on the logo and they could also be combined: large Spotify lines, smaller lines but further up, and capital text. Thoughts? How about coloring, I rather like this simple black and white look.

![Tekore2](https://user-images.githubusercontent.com/25202257/72270844-75bdf400-362e-11ea-81be-c85c4c65bf31.png)
![Tekore3](https://user-images.githubusercontent.com/25202257/72270850-7787b780-362e-11ea-964a-3fbeb70a5c6f.png)
![Tekore4](https://user-images.githubusercontent.com/25202257/72270857-79517b00-362e-11ea-97f8-e01376a78685.png)

**Comment by marioortizmanero** [comment]
I like the uppercase version the most too! To be honest I don't really see the differences between them, I didn't even realize that was a snake haha. Great job on the logo :) I'll upload it to the AUR soon.

**Comment by felix-hilden** [comment]
Good, then it's subtle enough :D Thanks!

**Comment by jingw222** [comment]
Fabulous work. Looks kinda dope. I'm all for it.
