### ISSUE TITLE
Feature request: Is there a library for Personalization API?

### ISSUE THREAD

**Issue by pixelicous** [felix-hilden/spotipy#129]
Browsing through the docs and code I think the following isn't integrated yet, am i right?
https://developer.spotify.com/documentation/web-api/reference-beta/#category-personalization
`
GET https://api.spotify.com/v1/me/top/{type}`

**Comment by pixelicous** [comment]
Nvm, got it

**Comment by felix-hilden** [comment]
Yes, and for others that may find this issue, the Personalisation API is a part of the client.
