### ISSUE TITLE
Timestamp handling

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#2]
Should timestamps be handled in some special way?

They are returned from the API in `YYYY-MM-DDTHH:MM:SSZ` zero-offset UTC. That precision may not be needed in displaying, but should be internally handled. The field could be an instance of datetime or perhaps a dataclass with an overrided `__str__` method to produce the original format.

**Comment by marioortizmanero** [comment]
The best way to handle timestamps is always with an existing module like `datetime` in my opinion. They can get messy and it's usually easier. At least if you have to manipulate the data to determine whether it's expired or not for example.

**Comment by felix-hilden** [comment]
Yeah, datetime should be used for sure if it's anything but the current string field. But using a dataclass or subclassing datetime and overriding `__str__` for either could automatically produce the same format that Spotify uses. The default `str` for `datetime` is `YYYY-MM-DD HH:MM:SS.microseconds`. I'm leaning towards parsing the date to a dataclass with one field like `date` as an instance of datetime and an overrided `__str__` method.

This is only for the date fields though. Token expiry is communicated with integers, and works fine as it is in [`Token.is_expiring()`](https://github.com/felix-hilden/spotipy/blob/master/spotipy/auth.py#L35).

**Comment by marioortizmanero** [comment]
Ah okay I misunderstood it. Yeah, a dataclass with an overrided `__str__` sounds like a solid plan. 

If the timestamps are limited to a class you could also consider a setter and getter for a @property inside it, but I'm not sure where the timestamps are actually used so it's probably not the best idea.
