### ISSUE TITLE
Equivalent for prompt_for_user_token

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/spotipy#28]
In the original API there was a very useful function called `prompt_for_user_token` in the `util` module that automatically got the access token and made the setup much easier. Currently, this API setup is something like this:

```python
scope = Scope(scopes.user_read_currently_playing)
client = Credentials(self._client_id, self._client_secret, self._redirect_uri)
url = client.authorisation_url(scope)
webbrowser.open(url)
print("Please paste the URL you were redirected to in your browser: ")
code = input()
token = client.request_access_token(code, scope)
self._token = token.split("?code=")[1].split("&")[0]
self._spotify = Spotify(self._token)
```

compared to:

```python
scope = 'user-read-currently-playing'
self._token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)
self._spotify = spotipy.Spotify(auth=self._token)
```

Now, I'm not sure if I'm using it correctly but there are a few problems here:
* Getting the scope is a really redundant process
* It doesn't load the keys from environment variables
* It doesn't try to automatically get the code from the pasted URL unless you use `self._token = token.split("?code=")[1].split("&")[0]`
* 9 lines of code vs 3 (although it's more "customizable")
* I'm not sure why the old API asks for a username when this one doesn't

**Comment by felix-hilden** [comment]
Yes! An equivalent `util` module is in the works, with only tests to write. And I planned to define a self-refreshing access token there as well.

I agree, it would be beneficial to be able to define scopes without the enumeration. That should be an option. I don't know the reason behind asking the user name, it is not needed for the authentication and can be retrieved afterwards via the `current_user` call.

**Comment by felix-hilden** [comment]
Accepting strings as scopes now an issue at #30

**Comment by marioortizmanero** [comment]
Hey @felix-hilden I've noticed that the `prompt_for_user_token` function you added doesn't try to use environment variables. It's as easy as this:
 
```python
    if not client_id:
        client_id = os.getenv('SPOTIPY_CLIENT_ID')
```

**Comment by felix-hilden** [comment]
Thanks for the suggestion, it was intentionally left out. I dislike the idea of having them in the function. Maybe a new utility could be introduced that reads those values. Which would then look like this:

```
id, secret, uri = read_env()
prompt_token(id, secret, uri)
```

but I'm not sure

**Comment by marioortizmanero** [comment]
It could also just be a different function that doesn't call prompt_token, just for the sake of standardizing the environment variable names used for this api.

**Comment by felix-hilden** [comment]
What do you mean? That a different function would provide the same functionality (and in addition read the environment) but not use the `prompt` function?

Also, after some thought I reckon the `read_env` function above is not such a great idea. It would read three environment values, which is trivial to write in case you happen to use environment variables to provide the credentials. It has little to do with `spotipy` itself. But I don't completely rule out the possibility that it's such an important use case that the library should support it.

**Comment by marioortizmanero** [comment]
Yeah, that's what I meant. But yeah put it that way it may be unnecessary. The point was to create said function so that the env names are "standarized" and so setting the env variables would work across different projects using this API.

**Comment by felix-hilden** [comment]
Ah, I see now. Maybe the `read_env` function would be the thing to implement in that case. One line of code more ought not to be such a hinderance. And one could even use tuple unpacking if all the values are defined.

```
*env = read_env()
prompt(*env)
```
