### ISSUE TITLE
__str__ method for RefreshingToken?

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/spotipy#33]
Do you think a `__str__` method on classes like RefreshingToken would help? Instead of having to do `s = Spotify(token.access_token)`, `s = Spotify(token)` would be enough and it'd make sense because there's not much more to do with a token.

Edit: my bad, `s = Spotify(token)` wouldn't actually call __str__ so this is kinda pointless. Sorry.

**Comment by felix-hilden** [comment]
I'm adding the object-based token stuff together when I move the client to return Model objects. I think `str(Token) == Token.access_token` would actually be a good idea! Unless it is better thought of as a model too, and the full JSON representation would be the `str`. Got to think about that. But passing a token object to the client is on its way!
