### ISSUE TITLE
Actions missing in CurrentlyPlaying

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/spotipy#38]
This [model](https://github.com/felix-hilden/spotipy/blob/master/spotipy/model/currently_playing.py) is apparently missing `actions`. You can see it [in the official docs](https://developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/). Not really sure if the models part is completely finished but I wanted to let you know.

```
    metadata = self._spotify.playback_currently_playing()
  File "/home/mario/.local/lib/python3.7/site-packages/spotipy/client/player.py", line 49, in playback_currently_playing
    return CurrentlyPlaying(**json)
TypeError: __init__() got an unexpected keyword argument 'actions'
```

E: whoops, I probably misread this [message](https://github.com/felix-hilden/spotipy/pull/37), sorry about that. Anyway, great job on the models :)

**Comment by felix-hilden** [comment]
Thanks for the info, yes I mean to finish the tests soon, but thank you for the information! The change was not intended to break anything so it's good to know.
