### ISSUE TITLE
Host documentation on Read The Docs

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#42]
Having documentation available in Read The Docs could be very beneficial. Investigate what is needed and what could be the best workflow of building the documentation, perhaps it could be done in continuous integration.

Currently waiting for the decision on project name in #22. If the transfer is successful, an issue to RTD should be opened to transfer the documentation name as well.

**Comment by marioortizmanero** [comment]
If you end up wanting me to upload this to the AUR, I should check if they'd allow a name transfer too.

**Comment by felix-hilden** [comment]
I'll close this issue, as the PyPI issue now holds the plan for RTD as well.
