### ISSUE TITLE
simplejson.errors.JSONDecodeError not excepted

### ISSUE THREAD

**Issue by bugflush** [felix-hilden/spotipy#44]
requests uses simplejson when available and only json.decoder.JSONDecodeError excepted on _parse_json

**Comment by felix-hilden** [comment]
Oh wow, I really appreciate you filing all these bugs! I'll have a look soon!

**Comment by felix-hilden** [comment]
It appears in [this discussion](https://github.com/psf/requests/issues/3052) the `requests` team decided to get rid of `simplejson` three years ago.

**Comment by bugflush** [comment]
just some notes:
- if I looked correctly. simplejson import only removed from not yet released requests3, but not from requests2
- on Ubuntu simplejson is still installed by default

(I removed simplejson from my system, so I don't actually care...)

**Comment by felix-hilden** [comment]
Hmm it appears I closed this too soon then. Much appreciated.

**Comment by felix-hilden** [comment]
Yeah, it was merged to a `proposed:3.0` branch. I dislike the idea of depending on simplejson just for this, so I think its better to test the response contents before trying deserialisation to see if it should be JSON. Then if we try to

**Comment by Bhanuprakash111** [comment]
> just some notes:
> 
> * if I looked correctly. simplejson import only removed from not yet released requests3, but not from requests2
> * on Ubuntu simplejson is still installed by default
> 
> (I removed simplejson from my system, so I don't actually care...)

how you removed that ??

**Comment by felix-hilden** [comment]
@Bhanuprakash111 Haven't worked with it, but most probably it's just a python package. So `pip uninstall simplejson` with your variants of `python2/3 -m` and `pip2/3` ought to do it.
