### ISSUE TITLE
PlaylistTrackObject.track can be null

### ISSUE THREAD

**Issue by bugflush** [felix-hilden/spotipy#45]
example playlist: spotify:playlist:6fzw3GiLktfRKczD6sl6mT
bug: https://github.com/spotify/web-api/issues/958

Traceback:
  File "spotipy/model/playlist.py", line 33, in __post_init__
    self.items = [PlaylistTrack(**t) for t in self.items]
  File "spotipy/model/playlist.py", line 33, in <listcomp>
    self.items = [PlaylistTrack(**t) for t in self.items]
  File "<string>", line 8, in __init__
  File "spotipy/model/playlist.py", line 24, in __post_init__
    self.track = FullTrack(**self.track)
TypeError: type object argument after ** must be a mapping, not NoneType

**Comment by bugflush** [comment]
This is actually documented feature:
"Information about the tracks of the playlist. Note, a track object may be null. This can happen if a track is no longer available."
https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/

**Comment by felix-hilden** [comment]
Reimplement this as a check on the track level as discussed in the PR review.
