### ISSUE TITLE
Scope-limited calls

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/spotipy#5]
Some calls require specific scopes or types of credentials to function.

For example:
- Featured playlists can be retrieved with application credentials
- Searching requires user credentials
- Some fields of a user request are provided only with certain scopes
- Playlist and follow modifications generally require scopes

Determine the credentials and scopes required for each call. Document them. Should access be restricted before a request or by catching an error from Spotify?

**Comment by felix-hilden** [comment]
Functions are now documented

**Comment by marioortizmanero** [comment]
Restricting the requests in Spotify may be confusing and annoying to deal with. The Spotify devs probably change the scopes from time to time and unexpected errors would be thrown if noone is actively maintaining the repo. Also, outdated versions of spotipy would be obsolete. But I'm unsure about how often these changes actually happen.

Maybe if somehow a test could make sure that the spotipy requirements are the same as the official ones it'd be easier to maintain.

**Comment by felix-hilden** [comment]
I agree. No idea if they change the specifications, I'd hope not. Perhaps between API versions, since this is v1. But that's a separate issue. Let's just make sure the errors carry enough meaning to the caller.
