### ISSUE TITLE
TypeError on current_user()

### ISSUE THREAD

**Issue by bugflush** [felix-hilden/spotipy#52]
`
spotipy/client/__init__.py", line 118, in current_user
    return PrivateUser(**json)
TypeError: __init__() got an unexpected keyword argument 'birthdate'
`
seems birthdate not mentioned on current documentation. It looks like: "birthdate": "2019-10-19"

**Comment by felix-hilden** [comment]
I have set a birthday on my account, but can't verify the result. Could I get some more information, an option in the client to send birthday info for example or any other info on your account that might affect the result?

**Comment by bugflush** [comment]
`
"birthdate": {
      "type": "string",
      "description": "The user's date-of-birth. This field is only available when the current user has granted access to the user-read-birthdate scope."
    },
`
https://github.com/spotify/web-api/blob/master/specifications/raml/schemas/current-user-profile.json

**Comment by bugflush** [comment]
and user-read-birthdate is not valid scope anymore
