### ISSUE TITLE
This is is great. Can you provide some examples for the new features?

### ISSUE THREAD

**Issue by shillshocked** [felix-hilden/spotipy#53]
I'm planning on porting a private project to this new version of Spotify. Previously mine was in Python 2.7. I find the new functionality encouraging, although could you elucidate with a few examples so I can see how they it might be used?

**Comment by felix-hilden** [comment]
I'm glad to hear that! The examples could be expanded, I agree. In the meantime build and have a look at the documentation. Particularly in the "advanced usage" section there are some ideas, but the modules themselves are not such long a read either.

**Comment by felix-hilden** [comment]
The readme of GitHub and also Sphinx documentation's index have been reorganised. The features are now more clearly listed and links are used in Sphinx to take a user to the relevant documents. This should be a better starting point for exploration, but some examples should still be added. Stay tuned.

**Comment by felix-hilden** [comment]
Now all the feature links take the user to concrete examples, either in the external documentation or the reference documentation of each module.
