### ISSUE TITLE
should models be frozen?

### ISSUE THREAD

**Issue by bugflush** [felix-hilden/spotipy#63]
```python
@dataclass(frozen=True)

**Comment by felix-hilden** [comment]
I think they should, and also have the `eq` method. Together they will provide immutability and a hash.

Some questions about equality arise then. The same objects should of course be equal if they are immutable. But for example the same song can have different IDs. So maybe the dataclasses own equality is enough.

**Comment by felix-hilden** [comment]
On the other hand, this makes further parsing in `post_init` more difficult.
