### ISSUE TITLE
add method get all items from Paging pages?

### ISSUE THREAD

**Issue by ghost** [felix-hilden/spotipy#65]
I think its pretty common use case. 

I currently use:
```python
    def all_pages_from_paging(self,
                              paging: Paging
                              ) -> Generator[Paging, None, None]:
        '''all pages from Paging generator'''
        yield paging
        while paging.next is not None:
            paging = self.next(paging)
            yield paging

    def all_items_from_paging(self,
                              paging: Paging
                              ) -> Generator[Item, None, None]:
        '''all items from Paging generator'''
        for page in self.all_pages_from_paging(paging):
            yield from page.items
```
and:
```python
paging = spotify.playlists('thesoundsofspotify')
print(paging.total)
for playlist in spotify.all_items_from_paging(paging):
     print(playlist.name)

**Comment by felix-hilden** [comment]
I like this, and agree it should be a pretty common use case.

**Comment by felix-hilden** [comment]
With #66, what would you think about this: `limit: Union[int, None] = api_default` and if greater than the api maximum, the paging objects are expanded with more items. If None, then all items are fetched.

I'm not sure how this would fit into the model structure, but it could be neat. Because the limits are needlessly low.

**Comment by bugflush** [comment]
I see #66 only for speeding up things. example on this issue takes 10 minutes with default limit and about 4 minutes with maximum limit.

**Comment by felix-hilden** [comment]
The behavior I mentioned could be implemented by assigning all items from the above generator to the paging attribute. But having it inside all functions that return pagings is maybe not such a good idea. So we'll leave it up for the users for now.
