### ISSUE TITLE
support shows and episodes

### ISSUE THREAD

**Issue by ghost** [felix-hilden/spotipy#69]
undocumented

... but search accepts 'episode' and 'show' type
... and self._get('episodes/' + episode_id, market=market) just like tracks

**Comment by bugflush** [comment]
https://github.com/spotify/web-api/issues/551

**Comment by bugflush** [comment]
just testing: https://gist.github.com/bugflush/d383a1c73921475a26b630d2da00976c

**Comment by felix-hilden** [comment]
I'm a little hesitant on implementing undocumented functionality even though it works. Let me think about it a while. I'm sure Spotify doesn't quite appreciate reverse engineering their API and I have seen some closed conversations regarding webhooks and such. But your code looks good.

**Comment by felix-hilden** [comment]
I'm leaning towards negative for now. But when some sort of official documentation is available, it should be implemented immediately. Thoughts, @marioortizmanero?

**Comment by marioortizmanero** [comment]
I also wouldn't implement this until the devs release proper documentation. For all we know it might just be a bug they could fix overnight.
