### ISSUE TITLE
Docs imply "refresh tokens" are ever-green, Spotify say they aren't

### ISSUE THREAD

**Issue by SHxKM** [felix-hilden/spotipy#86]
While they do a wonderful job at putting it in an obscure place, Spotify do state that refresh tokens may not be evergreen. In their "[Authorization Guide, Authorization Code Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow)" section, they write:

> A token that can be sent to the Spotify Accounts service in place of an authorization code. (When the access code expires, send a POST request to the Accounts service /api/token endpoint, but use this code in place of an authorization code. A new access token will be returned. **A new refresh token might be returned too.**)

I haven't built the docs and I don't quite remember where in the repo docs it's mentioned, but I'm pretty sure there's a section there that at least implies that refresh tokens don't expire. Perhaps the phrasing should be changed?

A more important change to make is in the code, in case spotipy doesn't currently handle this kind of response (one that also possibly includes a `refresh_token`).

**Comment by felix-hilden** [comment]
Thanks! While very uncommon in practice, in the OAuth2 [spec](https://tools.ietf.org/html/rfc6749#section-6) it is mentioned too. And more importantly it states that the server may revoke the old refresh token. But I have sucessfully used the same one for the tests of this repository for several months now.

Code-wise we are ok. `Credentials` managers inject the old refresh token only if it is empty in the refresh response and `RefreshToken` uses whatever the `refresh_token` currently is. But the docs should be changed.
